on: [push]

jobs:
  deploy_manifests_job:
    runs-on: ubuntu-latest
    name: A job to deploy kubernetes manifests files on OpenShift Clusters 
    steps:
    # Checkout current repository
    - name: Checkout
      uses: actions/checkout@v1
    # Deploy manifests step
    - name: Deploy to OpenShift action step
      id: deploy
      uses: rawc0der/deploy-manifests-openshift-action@v0.0.1
      # with:
        # oc-token: 'XXXXXXXXX-ZZZZZZZZZ_XXXXXXXX'
        # oc-server: 'https://api.us-east-2.starter.openshift-online.com:6443'
        # oc-source-path: 'deploy/'
        # oc-namespace: 'rawdata'
        # oc-use-insecure: 'false'
      env:
        OC_TOKEN: ${{ secrets.OC_TOKEN }}
        OC_SERVER: ${{ secrets.OC_SERVER }}
        OC_SOURCE_PATH: 'deploy/'
        OC_NAMESPACE: 'rawdata'  
        OC_USE_INSECURE: 'false'
    # View the output from the `deploy` step
    - name: Check the cluster status
      run: echo "${{ steps.deploy.outputs.status }}"